[package]
name = "cert"
version = "0.1.0"
authors = ["Filip Skubacz <filip.skubacz00@gmail.com>"]
edition = "2018"

[dependencies]
pyo3 = { version = "0.14.2", features = ["auto-initialize"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
